### PR TITLE
Feat/map center entry update

### PR DESCRIPTION
**Pull request by DarinHajou**
### Enhanced Map Center Functionality

We've refined our map center functionalities to better manage location data for different user interactions—specifically, searching and selling activities.

Key Update:
Introduced a 'type' property to the map center functions, enabling distinct handling of search and sell center coordinates. 

This change streamlines our map operations, making them more adaptable to user-specific needs and interactions.

### CODE REVIEW

**Comment by swoocn** [comment]
Hi @DarinHajou - I made some adjustments to your PR.  Feel free to review to better understand the changes.  Overall, it appears the integration is broken, but I take it that you're aware and will fix it in your recovered PR?

**Review by DarinHajou — COMMENTED** [review]
LGTM!

**Comment by swoocn** [comment]
> LGTM!

Great effort! I made a few additional adjustments, but overall, the backend looks well-polished. I’ll be standing by for your corresponding frontend updates. Keep up the awesome work, @DarinHajou! 😎👍

**Review by swoocn — APPROVED** [review]
Approved; though suggested to wait till corresponding frontend changes are ready before merging this PR.

**Pull request merged**
